apiVersion: apps/v1
kind: Deployment
metadata:
 name: devops-api
 labels:
   app: devops-api
spec:
 strategy:
   rollingUpdate:
     maxSurge: 25%
     maxUnavailable: 25%
   type: RollingUpdate
 replicas: 4
 selector:
   matchLabels:
     app: devops-api
 template:
   metadata:
     labels:
       app: devops-api
   spec:
     containers:
     - name: devops-api
       image: kaizenacademy/api-app:1.0.0
       ports:
       - containerPort: 3001
       env:
       - name: DBUSER
         valueFrom:
           configMapKeyRef:
             name: devops-api-config
             key: DBUSER
       - name: DB
         valueFrom:
           configMapKeyRef:
             name: devops-api-config
             key: DB
       - name: DBPASS
         valueFrom:
           secretKeyRef:
             name: devops-api-secret
             key: DBPASS
       - name: DBHOST
         valueFrom:
           configMapKeyRef:
             name: devops-api-config
             key: DBHOST
       - name: DBPORT
         valueFrom:
           configMapKeyRef:
             name: devops-api-config
             key: DBPORT
       - name: PORT
         valueFrom:
           configMapKeyRef:
             name: devops-api-config
             key: PORT
       readinessProbe:
         httpGet:
           path: /health
           port: 3001
         initialDelaySeconds: 10
         periodSeconds: 10
       livenessProbe:
         httpGet:
           path: /health
           port: 3001
         initialDelaySeconds: 10
         periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
 name: devops-api
spec:
 selector:
   app: devops-api
 ports:
 - protocol: TCP
   port: 3001
   targetPort: 3001
 type: LoadBalancer
