apiVersion: v1
kind: ConfigMap
metadata:
 name: devops-api-config
data:
 DB: devops_db
 DBUSER: devops_user
 DBHOST: mysql
 DBPORT: "3306"
 PORT: "3001"
---
apiVersion: v1
kind: Secret
metadata:
 name: devops-api-secret
type: Opaque
data:
 DBPASS: cGFzc3dvcmQ=   # base64 encoded password