apiVersion: apps/v1
kind: Deployment
metadata:
 name: devops-api
 labels:
   app: devops-api
spec:
 replicas: 1
 selector:
   matchLabels:
     app: devops-api
 template:
   metadata:
     labels:
       app: devops-api
   spec:
     containers:
     - name: devops-api
       image: sani21/api-app:1.0.0
       ports:
       - containerPort: 3001
       env:
       - name: DB
         value: devops_db
       - name: DBUSER
         value: devops_user
       - name: DBPASS
         value: password
       - name: DBHOST
         value: mysql
       - name: DBPORT
         value: "3306"
       - name: PORT
         value: "3001"
---
apiVersion: v1
kind: Service
metadata:
 name: devops-api
spec:
 selector:
   app: devops-api
 ports:
 - protocol: TCP
   port: 3001
   targetPort: 3001
 type: LoadBalancer
