apiVersion: apps/v1
kind: Deployment
metadata:
 name: devops-web
 labels:
   app: devops-web
spec:
 replicas: 1
 selector:
   matchLabels:
     app: devops-web
 template:
   metadata:
     labels:
       app: devops-web
   spec:
     containers:
     - name: devops-web
       image: sani21/web-app:1.0.0
       ports:
       - containerPort: 3000
       env:
       - name: API_HOST
         value: http://devops-api:3001
       - name: PORT
         value: "3000"
---
apiVersion: v1
kind: Service
metadata:
 name: devops-web
spec:
 selector:
   app: devops-web
 ports:
 - protocol: TCP
   port: 3001
   targetPort: 3001
 type: LoadBalancer